In [2]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:

rand = np.random.RandomState(52)#here 1st time whatever it is generated it will remain the same in al execution
x = rand.randint(100,size=10)
print(x)

[28 11 13 23 86 28 32 69 11 91]


In [4]:
#1d array
print([x[3],x[7],x[2]])
ind=[3,7,4]
x[ind]

[23, 69, 13]


array([23, 69, 86])

In [5]:
#2d array
ind=np.array([[3,7],
              [4,5]])
print(ind)
print(x[ind])#here element of array is used as index

[[3 7]
 [4 5]]
[[23 69]
 [86 28]]


In [6]:
x2=np.array([(1,2,3),(11,22,33)])
print(x2)
print(x2.ndim)
print("Each item contains",x2.itemsize,"bytes")
print("Shape:",x2.shape)
print("Each item is of the type",x2.dtype)



[[ 1  2  3]
 [11 22 33]]
2
Each item contains 8 bytes
Shape: (2, 3)
Each item is of the type int64


In [7]:
print(np.add.reduce(x2))#it will add the coloumn
print(sum(x2))#add all the element
print(np.sum(x2))#summation of all element

[12 24 36]
[12 24 36]
72


In [8]:
a=np.array([[1,2],[3,4],[5,6]])
print("original")
print(a)
a=a.reshape(2,3)
print("reshaped array")
print(a)
a=a.reshape(1,6)
print(a)
a=a.reshape(6,1)
print(a)
#=a.reshape(5,1)#this is an array as there is only 6 element so 2x3,2x6,6x1,3x2 is possible
# print(a)


original
[[1 2]
 [3 4]
 [5 6]]
reshaped array
[[1 2 3]
 [4 5 6]]
[[1 2 3 4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [9]:
a=np.arange(12).reshape((3,4))#max 12 element then it will arrange
print(a)
print(a[1,2])
print(a[1,[2,0,1]])#it print the value of 1x2,1x0,1x1(this is called combined indeing)
print(a[1:3,1:3])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
6
[6 4 5]
[[ 5  6]
 [ 9 10]]


In [10]:
print(a)
print("max=",a.max())
print("min=",a.min())
print("sum=",a.sum())
print("max column=",a.max(axis=0))#axis=0 means col,1 means row
print("max row=",a.max(axis=1))
print("max row sum=",a.sum(axis=1))
print("max col sum=",a.sum(axis=0))
print("srt",np.sqrt(a))
print("standard deviation",np.std(a))
print("standard deviation",a.std(axis=1))
print("standard deviation",a.std(axis=0))




[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
max= 11
min= 0
sum= 66
max column= [ 8  9 10 11]
max row= [ 3  7 11]
max row sum= [ 6 22 38]
max col sum= [12 15 18 21]
srt [[0.         1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974 2.64575131]
 [2.82842712 3.         3.16227766 3.31662479]]
standard deviation 3.452052529534663
standard deviation [1.11803399 1.11803399 1.11803399]
standard deviation [3.26598632 3.26598632 3.26598632 3.26598632]


In [11]:
a=np.array([[1,2],[3,4],[5,6]])
print("a",a)
b=np.array([[1,2],[3,4],[5,6]])
print("a",b)
print("sum",a+b)
print("substraction",a-b)
print("multiply",a*b)
print("devide",a/b)
print("multiply one number with all",a*3)



a [[1 2]
 [3 4]
 [5 6]]
a [[1 2]
 [3 4]
 [5 6]]
sum [[ 2  4]
 [ 6  8]
 [10 12]]
substraction [[0 0]
 [0 0]
 [0 0]]
multiply [[ 1  4]
 [ 9 16]
 [25 36]]
devide [[1. 1.]
 [1. 1.]
 [1. 1.]]
multiply one number with all [[ 3  6]
 [ 9 12]
 [15 18]]


In [12]:
#array concatentation
print("Array a\n {} \n Array b \n{}".format(a,b))
print("vertical concatenation\n",np.vstack((a,b)))
print("horizontal concatenation\n",np.hstack((a,b)))


Array a
 [[1 2]
 [3 4]
 [5 6]] 
 Array b 
[[1 2]
 [3 4]
 [5 6]]
vertical concatenation
 [[1 2]
 [3 4]
 [5 6]
 [1 2]
 [3 4]
 [5 6]]
horizontal concatenation
 [[1 2 1 2]
 [3 4 3 4]
 [5 6 5 6]]


In [13]:
name=np.array(["bob","will","tom","bob"])
print(name)
x=rand.randint(100,size=(4,4))

['bob' 'will' 'tom' 'bob']


In [14]:
name=="bob"

array([ True, False, False,  True])

In [15]:
x[name=='bob']

array([[35, 99, 97, 99],
       [45, 79, 54, 76]])

In [16]:
value = rand.randint(100,size=(6,6))
print(value)


[[63 39 22 71 39  7]
 [63 20 34 43 78 84]
 [74 64 59 63 65 82]
 [ 6 25 86 15 95 85]
 [26  0 90 38 30 49]
 [ 9 87 17 74 25 89]]


In [17]:
value[(0,1,2,3,4),(1,2,3,4,5)]

array([39, 34, 63, 95, 49])

In [18]:
value[3:,[0,2,5]]

array([[ 6, 86, 85],
       [26, 90, 49],
       [ 9, 17, 89]])

In [19]:
mask=np.array([1,0,1,0,0,1],dtype=bool)
value[mask,2]


array([22, 59, 17])

In [22]:
#sorting array
x=np.array([10,6,8,2,5,4,9,1])
print(np.sort(x))
print(np.sort(x)[::-1])
print(np.argsort(x))#it sort the index
print(x[np.argsort(x)])
print(x[np.argsort(-x)])


[ 1  2  4  5  6  8  9 10]
[7 3 5 4 1 2 6 0]
[ 1  2  4  5  6  8  9 10]
[10  9  8  6  5  4  2  1]


In [41]:
#sorting along rows and column
rand=np.random.RandomState(42)
x=rand.randint(0,10,(4,6))
print(x)
print(np.sort(x,axis=0))#according to column
print(np.sort(x,axis=1))#according to row


[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]
[[2 1 4 0 1 5]
 [5 2 5 4 3 7]
 [6 3 7 4 6 7]
 [7 6 7 4 9 9]]
[[3 4 6 6 7 9]
 [2 3 4 6 7 7]
 [1 2 4 5 7 7]
 [0 1 4 5 5 9]]


In [45]:
print(np.sort(x,axis=1)[::-1])#reverse
print(np.sort(x,axis=0)[::-1])#reverse



[[0 1 4 5 5 9]
 [1 2 4 5 7 7]
 [2 3 4 6 7 7]
 [3 4 6 6 7 9]]
[[7 6 7 4 9 9]
 [6 3 7 4 6 7]
 [5 2 5 4 3 7]
 [2 1 4 0 1 5]]


In [46]:
dtype=[('person_name','U9'),('person_age','i8'),('is_python_programmer','bool')]
data = np.array([('ram',25,True),('Sita',23,False),('Lakshman',27,True),('Ravan',27,True)],dtype=dtype)
data

array([('ram', 25,  True), ('Sita', 23, False), ('Lakshman', 27,  True),
       ('Ravan', 27,  True)],
      dtype=[('person_name', '<U9'), ('person_age', '<i8'), ('is_python_programmer', '?')])