In [95]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [96]:

rand = np.random.RandomState(52)#here 1st time whatever it is generated it will remain the same in al execution
x = rand.randint(100,size=10)
print(x)

[28 11 13 23 86 28 32 69 11 91]


In [97]:
#1d array
print([x[3],x[7],x[2]])
ind=[3,7,4]
x[ind]

[23, 69, 13]


array([23, 69, 86])

In [98]:
#2d array
ind=np.array([[3,7],
              [4,5]])
print(ind)
print(x[ind])#here element of array is used as index

[[3 7]
 [4 5]]
[[23 69]
 [86 28]]


In [99]:
x2=np.array([(1,2,3),(11,22,33)])
print(x2)
print(x2.ndim)
print("Each item contains",x2.itemsize,"bytes")
print("Shape:",x2.shape)
print("Each item is of the type",x2.dtype)



[[ 1  2  3]
 [11 22 33]]
2
Each item contains 8 bytes
Shape: (2, 3)
Each item is of the type int64


In [100]:
print(np.add.reduce(x2))#it will add the coloumn
print(sum(x2))#add all the element
print(np.sum(x2))#summation of all element

[12 24 36]
[12 24 36]
72


In [101]:
a=np.array([[1,2],[3,4],[5,6]])
print("original")
print(a)
a=a.reshape(2,3)
print("reshaped array")
print(a)
a=a.reshape(1,6)
print(a)
a=a.reshape(6,1)
print(a)
#=a.reshape(5,1)#this is an array as there is only 6 element so 2x3,2x6,6x1,3x2 is possible
# print(a)


original
[[1 2]
 [3 4]
 [5 6]]
reshaped array
[[1 2 3]
 [4 5 6]]
[[1 2 3 4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [102]:
a=np.arange(12).reshape((3,4))#max 12 element then it will arrange
print(a)
print(a[1,2])
print(a[1,[2,0,1]])#it print the value of 1x2,1x0,1x1(this is called combined indeing)
print(a[1:3,1:3])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
6
[6 4 5]
[[ 5  6]
 [ 9 10]]


In [103]:
print(a)
print("max=",a.max())
print("min=",a.min())
print("sum=",a.sum())
print("max column=",a.max(axis=0))#axis=0 means col,1 means row
print("max row=",a.max(axis=1))
print("max row sum=",a.sum(axis=1))
print("max col sum=",a.sum(axis=0))
print("srt",np.sqrt(a))
print("standard deviation",np.std(a))
print("standard deviation",a.std(axis=1))
print("standard deviation",a.std(axis=0))




[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
max= 11
min= 0
sum= 66
max column= [ 8  9 10 11]
max row= [ 3  7 11]
max row sum= [ 6 22 38]
max col sum= [12 15 18 21]
srt [[0.         1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974 2.64575131]
 [2.82842712 3.         3.16227766 3.31662479]]
standard deviation 3.452052529534663
standard deviation [1.11803399 1.11803399 1.11803399]
standard deviation [3.26598632 3.26598632 3.26598632 3.26598632]


In [104]:
a=np.array([[1,2],[3,4],[5,6]])
print("a",a)
b=np.array([[1,2],[3,4],[5,6]])
print("a",b)
print("sum",a+b)
print("substraction",a-b)
print("multiply",a*b)
print("devide",a/b)
print("multiply one number with all",a*3)



a [[1 2]
 [3 4]
 [5 6]]
a [[1 2]
 [3 4]
 [5 6]]
sum [[ 2  4]
 [ 6  8]
 [10 12]]
substraction [[0 0]
 [0 0]
 [0 0]]
multiply [[ 1  4]
 [ 9 16]
 [25 36]]
devide [[1. 1.]
 [1. 1.]
 [1. 1.]]
multiply one number with all [[ 3  6]
 [ 9 12]
 [15 18]]


In [108]:
#array concatentation
print("Array a\n {} \n Array b \n{}".format(a,b))
print("vertical concatenation\n",np.vstack((a,b)))
print("horizontal concatenation\n",np.hstack((a,b)))


Array a
 [[1 2]
 [3 4]
 [5 6]] 
 Array b 
[[1 2]
 [3 4]
 [5 6]]
vertical concatenation
 [[1 2]
 [3 4]
 [5 6]
 [1 2]
 [3 4]
 [5 6]]
horizontal concatenation
 [[1 2 1 2]
 [3 4 3 4]
 [5 6 5 6]]
